<?php

declare(strict_types=1);

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\Brand\Models\Brand;
use Modules\Category\Models\Category;
use Modules\Product\Models\Product;

class RataplamStoreSeeder extends Seeder
{
    public function run(): void
    {
        $brand = Brand::create([
            'title' => 'Rataplam',
            'slug' => 'rataplam',
            'status' => 'active',
        ]);

        $catBebe = Category::create(['title' => 'Bebê', 'slug' => 'bebe', 'status' => 'active', 'parent_id' => null]);
        $catAcessorios = Category::create(['title' => 'Acessórios', 'slug' => 'acessorios', 'status' => 'active', 'parent_id' => null]);
        $catBermudas = Category::create(['title' => 'Bermudas', 'slug' => 'bermudas', 'status' => 'active', 'parent_id' => null]);
        $catBlusas = Category::create(['title' => 'Blusas', 'slug' => 'blusas', 'status' => 'active', 'parent_id' => null]);
        $catBiquinis = Category::create(['title' => 'Biquínis', 'slug' => 'biquinis', 'status' => 'active', 'parent_id' => null]);
        $catCalcas = Category::create(['title' => 'Calças', 'slug' => 'calcas', 'status' => 'active', 'parent_id' => null]);
        $catMeninos = Category::create(['title' => 'Meninos', 'slug' => 'meninos', 'status' => 'active', 'parent_id' => null]);
        $catMeninas = Category::create(['title' => 'Meninas', 'slug' => 'meninas', 'status' => 'active', 'parent_id' => null]);

        $products = [
            // Bebê
            ['title' => 'Conjunto Navy', 'price' => 129.90, 'summary' => 'Conjunto infantil navy composto por body e calça. Confortável e estiloso para o dia a dia do seu bebê.', 'description' => 'Conjunto infantil navy em algodão macio. Perfeito para bebês, composto por body com botões de pressão e calça com elástico na cintura. Estampa navy clássica e atemporal.', 'stock' => 0, 'image_url' => 'conjunto-navy', 'categories' => [$catBebe->id]],
            ['title' => 'Vestido Celebrare', 'price' => 69.90, 'summary' => 'Vestido delicado para bebê, ideal para ocasiões especiais.', 'description' => 'Vestido Celebrare em tecido leve e confortável. Com detalhes em renda e laço, perfeito para festas e celebrações. Disponível em vários tamanhos.', 'stock' => 10, 'image_url' => 'vestido-celebrare', 'categories' => [$catBebe->id, $catMeninas->id]],
            ['title' => 'Macacão Rita', 'price' => 74.90, 'summary' => 'Macacão infantil Rita com estampa florida. Alegre e confortável.', 'description' => 'Macacão Rita com estampa floral encantadora. Confeccionado em algodão premium, com botões de pressão para facilitar a troca. Ideal para dias quentes.', 'stock' => 15, 'image_url' => 'macacao-rita', 'categories' => [$catBebe->id, $catMeninas->id]],
            ['title' => 'Macacão Sansão', 'price' => 74.90, 'summary' => 'Macacão Sansão com estampa temática. Conforto e estilo para o bebê.', 'description' => 'Macacão Sansão em algodão macio com estampa lúdica. Mangas curtas e pernas compridas, fechamento frontal com botões de pressão.', 'stock' => 12, 'image_url' => 'macacao-sansao', 'categories' => [$catBebe->id, $catMeninos->id]],
            ['title' => 'Conjunto Nature', 'price' => 139.90, 'summary' => 'Conjunto Nature com temática natural. Estilo e conforto.', 'description' => 'Conjunto infantil Nature em tons terrosos. Composto por body manga longa e calça com pés. Estampa de animais e elementos da natureza.', 'stock' => 0, 'image_url' => 'conjunto-nature', 'categories' => [$catBebe->id]],
            ['title' => 'Vestido Delicate', 'price' => 98.90, 'summary' => 'Vestido Delicate com detalhes em renda. Elegância para sua bebê.', 'description' => 'Vestido Delicate em tom pastel com aplicações de renda e bordados delicados. Mangas bufantes e saia rodada. Fechamento nas costas com botão.', 'stock' => 8, 'image_url' => 'vestido-delicate', 'categories' => [$catBebe->id, $catMeninas->id]],
            ['title' => 'Body Sansão', 'price' => 42.90, 'summary' => 'Body Sansão em algodão macio. Básico e confortável.', 'description' => 'Body Sansão em algodão 100% com estampa divertida. Mangas curtas, fechamento por botões de pressão na altura da virilha. Conforto absoluto.', 'stock' => 20, 'image_url' => 'body-sansao', 'categories' => [$catBebe->id]],
            ['title' => 'Macacão Cachorro', 'price' => 94.90, 'summary' => 'Macacão Cachorro com estampa de cachorrinhos. Fofo e divertido.', 'description' => 'Macacão Cachorro em algodão com estampa de cachorrinhos. Modelo com capuz e orelhas de cachorro. Fechamento frontal com zíper.', 'stock' => 10, 'image_url' => 'macacao-cachorro', 'categories' => [$catBebe->id, $catMeninos->id]],
            ['title' => 'Macacão Nemo', 'price' => 82.90, 'summary' => 'Macacão Nemo com tema aquático. Perfeito para o verão.', 'description' => 'Macacão Nemo com estampa de peixes e tema aquático. Algodão fresco, mangas curtas e pernas compridas. Botões de pressão.', 'stock' => 14, 'image_url' => 'macacao-nemo', 'categories' => [$catBebe->id]],
            ['title' => 'Macacão Cara de Urso', 'price' => 149.90, 'summary' => 'Macacão Cara de Urso com capuz. Quentinho e divertido.', 'description' => 'Macacão Cara de Urso em malha peluciada quente. Com capuz e orelhas de urso, perfeito para dias frios. Fechamento com zíper frontal.', 'stock' => 0, 'image_url' => 'macacao-cara-de-urso', 'categories' => [$catBebe->id]],
            ['title' => 'Macacão ABC', 'price' => 129.90, 'summary' => 'Macacão ABC com estampa alfabética. Educativo e estiloso.', 'description' => 'Macacão ABC em algodão com estampa de letras do alfabeto. Colorido e divertido, perfeito para estimular o aprendizado. Fechamento por botões.', 'stock' => 0, 'image_url' => 'macacao-abc', 'categories' => [$catBebe->id]],
            ['title' => 'Macacão Transportes', 'price' => 148.90, 'summary' => 'Macacão Transportes com estampa de veículos. Aventura diária.', 'description' => 'Macacão Transportes com estampa de carros, aviões e navios. Algodão premium, modelagem confortável com pés embutidos.', 'stock' => 7, 'image_url' => 'macacao-transportes', 'categories' => [$catBebe->id, $catMeninos->id]],
            ['title' => 'Macacão Cogumelo', 'price' => 137.90, 'summary' => 'Macacão Cogumelo com estampa lúdica de cogumelos.', 'description' => 'Macacão Cogumelo em algodão orgânico com estampa de cogumelos coloridos. Macio, confortável e cheio de charme.', 'stock' => 9, 'image_url' => 'macacao-cogumelo', 'categories' => [$catBebe->id]],
            ['title' => 'Conjunto Deby', 'price' => 189.90, 'summary' => 'Conjunto Deby completo para bebê. Estilo premium.', 'description' => 'Conjunto Deby em malha de alta qualidade. Inclui body, calça e casaquinho. Presente ideal para bebês.', 'stock' => 5, 'image_url' => 'conjunto-deby', 'categories' => [$catBebe->id]],
            ['title' => 'Macacão Leo', 'price' => 136.90, 'summary' => 'Macacão Leo com estampa de leão. Corajoso e confortável.', 'description' => 'Macacão Leo com estampa de leão em algodão de alta qualidade. Modelagem confortável, fechamento frontal com botões de pressão.', 'stock' => 11, 'image_url' => 'macacao-leo', 'categories' => [$catBebe->id]],
            ['title' => 'Macacão Flor', 'price' => 137.90, 'summary' => 'Macacão Flor com estampa floral encantadora.', 'description' => 'Macacão Flor em algodão com estampa floral delicada. Perfeito para bebês, com botões de pressão na parte frontal e entre as pernas.', 'stock' => 8, 'image_url' => 'macacao-flor', 'categories' => [$catBebe->id, $catMeninas->id]],
            ['title' => 'Macacão Selva', 'price' => 137.90, 'summary' => 'Macacão Selva com estampa de animais selvagens.', 'description' => 'Macacão Selva em algodão com estampa de animais da selva. Aventureiro e confortável para o bebê explorar o mundo.', 'stock' => 6, 'image_url' => 'macacao-selva', 'categories' => [$catBebe->id]],
            ['title' => 'Macacão Abelhas', 'price' => 137.90, 'summary' => 'Macacão Abelhas com estampa de abelhas divertidas.', 'description' => 'Macacão Abelhas em algodão com estampa de abelhas e flores. Colorido e alegre, perfeito para a primavera.', 'stock' => 10, 'image_url' => 'macacao-abelhas', 'categories' => [$catBebe->id]],
            ['title' => 'Macacão Luiza', 'price' => 152.90, 'summary' => 'Macacão Luiza com detalhes em renda. Elegância para bebê.', 'description' => 'Macacão Luiza em algodão com detalhes em renda e bordados. Modelagem princesa com saia embutida e flor decorativa.', 'stock' => 7, 'image_url' => 'macacao-luiza', 'categories' => [$catBebe->id, $catMeninas->id]],
            ['title' => 'Macacão Beni', 'price' => 168.90, 'summary' => 'Macacão Beni premium. Sofisticação para o seu bebê.', 'description' => 'Macacão Beni em malha premium com estampa exclusiva. Design moderno e confortável com acabamento impecável.', 'stock' => 4, 'image_url' => 'macacao-beni', 'categories' => [$catBebe->id]],

            // Acessórios
            ['title' => 'Sapatinho Tricô Time', 'price' => 38.90, 'summary' => 'Sapatinho de tricô time. Macio e delicado.', 'description' => 'Sapatinho de tricô feito à mão com temática de time. Confortável e quentinho para os pezinhos do bebê. Presente perfeito.', 'stock' => 25, 'image_url' => 'sapatinho-trico-time', 'categories' => [$catAcessorios->id, $catBebe->id]],
            ['title' => 'Sapatinho Tricô Bota', 'price' => 38.90, 'summary' => 'Sapatinho de tricô modelo bota. Fofo e estiloso.', 'description' => 'Sapatinho de tricô em formato de bota. Feito à mão com carinho, mantém os pés aquecidos com muito estilo.', 'stock' => 20, 'image_url' => 'sapatinho-trico-bota', 'categories' => [$catAcessorios->id, $catBebe->id]],
            ['title' => 'Sapatinho Tricô Bicolor', 'price' => 38.90, 'summary' => 'Sapatinho de tricô bicolor. Colorido e alegre.', 'description' => 'Sapatinho de tricô bicolor feito à mão. Combinação de duas cores que encantam. Macio e confortável.', 'stock' => 22, 'image_url' => 'sapatinho-trico-bicolor', 'categories' => [$catAcessorios->id, $catBebe->id]],
            ['title' => 'Toalha Batizado', 'price' => 59.90, 'summary' => 'Toalha de batizado bordada. Peça especial para momento único.', 'description' => 'Toalha de batizado em algodão com bordado delicado e renda. Perfeita para o momento especial do batizado. Medidas generosas.', 'stock' => 15, 'image_url' => 'toalha-batizado', 'categories' => [$catAcessorios->id, $catBebe->id]],
            ['title' => 'Colete Tricô Trick', 'price' => 134.90, 'summary' => 'Colete de tricô Trick. Elegante e quentinho.', 'description' => 'Colete de tricô Trick em ponto fantasia. Versátil, combina com diversas produções. Perfeito para dias amenos.', 'stock' => 8, 'image_url' => 'colete-trico-trick', 'categories' => [$catAcessorios->id]],
            ['title' => 'Sapatinho Tricô Liso', 'price' => 38.90, 'summary' => 'Sapatinho de tricô liso. Clássico e delicado.', 'description' => 'Sapatinho de tricô liso feito à mão em cores neutras. Clássico e elegante, combina com qualquer look do bebê.', 'stock' => 30, 'image_url' => 'sapatinho-trico', 'categories' => [$catAcessorios->id, $catBebe->id]],

            // Bermudas
            ['title' => 'Bermuda Cuca', 'price' => 21.90, 'summary' => 'Bermuda Cuca alegre e colorida para crianças.', 'description' => 'Bermuda infantil Cuca com estampa divertida. Cintura com elástico, algodão macio e fresco. Perfeita para brincar.', 'stock' => 30, 'image_url' => 'bermuda-cuca', 'categories' => [$catBermudas->id, $catMeninos->id]],
            ['title' => 'Bermuda Bob', 'price' => 62.90, 'summary' => 'Bermuda Bob confortável e estilosa.', 'description' => 'Bermuda infantil Bob com estampa temática. Cintura ajustável com elástico e cordão. Bolsos laterais e tecido resistente.', 'stock' => 18, 'image_url' => 'bermuda-bob', 'categories' => [$catBermudas->id, $catMeninos->id]],
            ['title' => 'Bermuda Gamer', 'price' => 109.90, 'summary' => 'Bermuda Gamer com temática de games.', 'description' => 'Bermuda Gamer em sarja com estampa de videogame. Cintura com elástico, bolsos funcionais e modelagem moderna.', 'stock' => 12, 'image_url' => 'bermuda-gamer', 'categories' => [$catBermudas->id, $catMeninos->id]],
            ['title' => 'Bermuda Show', 'price' => 112.90, 'summary' => 'Bermuda Show com brilho e estilo.', 'description' => 'Bermuda Show com detalhes brilhantes e estampa especial. Perfeita para festas e ocasiões especiais. Tecido confortável.', 'stock' => 0, 'image_url' => 'bermuda-show', 'categories' => [$catBermudas->id, $catMeninos->id]],
            ['title' => 'Bermuda Kayke', 'price' => 84.90, 'summary' => 'Bermuda Kayke em sarja. Resistente e estilosa.', 'description' => 'Bermuda Kayke em sarja azul. Cintura com elástico, bolsos laterais e traseiros. Ideal para o dia a dia.', 'stock' => 20, 'image_url' => 'bermuda-kayke', 'categories' => [$catBermudas->id, $catMeninos->id]],
            ['title' => 'Bermuda Play', 'price' => 112.90, 'summary' => 'Bermuda Play com estampa de brinquedos.', 'description' => 'Bermuda Play em algodão com estampa de brinquedos clássicos. Confortável, com cintura elástica e bolsos.', 'stock' => 15, 'image_url' => 'bermuda-play', 'categories' => [$catBermudas->id, $catMeninos->id]],
            ['title' => 'Bermuda Vida', 'price' => 54.90, 'summary' => 'Bermuda Vida estampada. Leve e fresca.', 'description' => 'Bermuda Vida em viscolycra com estampa vibrante. Ideal para dias quentes, com cintura elástica e caimento perfeito.', 'stock' => 25, 'image_url' => 'bermuda-vida', 'categories' => [$catBermudas->id, $catMeninos->id]],
            ['title' => 'Bermuda Rasga', 'price' => 114.90, 'summary' => 'Bermuda Rasga com estilo despojado.', 'description' => 'Bermuda Rasga em jeans com detalhes rasgados. Modelagem moderna e despojada, com cintura ajustável.', 'stock' => 0, 'image_url' => 'bermuda-rasga', 'categories' => [$catBermudas->id, $catMeninos->id]],
            ['title' => 'Bermuda Naipe', 'price' => 64.90, 'summary' => 'Bermuda Naipe com estampa de cartas.', 'description' => 'Bermuda Naipe em algodão com estampa de naipes. Cintura elástica, tecido leve e fresco. Perfeita para o verão.', 'stock' => 18, 'image_url' => 'bermuda-naipe', 'categories' => [$catBermudas->id, $catMeninos->id]],
            ['title' => 'Bermuda Pepe', 'price' => 62.90, 'summary' => 'Bermuda Pepe em sarja. Clássica e confortável.', 'description' => 'Bermuda Pepe em sarja bege. Com cintura elástica e cordão, bolsos laterais. Básica e versátil.', 'stock' => 22, 'image_url' => 'bermuda-pepe', 'categories' => [$catBermudas->id, $catMeninos->id]],
            ['title' => 'Bermuda Omar', 'price' => 52.90, 'summary' => 'Bermuda Omar colorida e alegre.', 'description' => 'Bermuda Omar em algodão colorido. Cintura elástica, fresca e confortável. Ideal para brincadeiras ao ar livre.', 'stock' => 20, 'image_url' => 'bermuda-omar', 'categories' => [$catBermudas->id, $catMeninos->id]],
            ['title' => 'Bermuda Zion', 'price' => 49.90, 'summary' => 'Bermuda Zion em moletom. Quente e confortável.', 'description' => 'Bermuda Zion em moletom cinza. Com cintura elástica e cordão, bolsos laterais. Perfeita para dias mais frescos.', 'stock' => 16, 'image_url' => 'bermuda-zion', 'categories' => [$catBermudas->id, $catMeninos->id]],
            ['title' => 'Bermuda Explorer', 'price' => 69.90, 'summary' => 'Bermuda Explorer para pequenos aventureiros.', 'description' => 'Bermuda Explorer em sarja com estampa de bússola e mapa. Cintura elástica, bolsos com botão. Aventura e estilo.', 'stock' => 14, 'image_url' => 'bermuda-explore', 'categories' => [$catBermudas->id, $catMeninos->id]],
            ['title' => 'Bermuda Positive', 'price' => 124.90, 'summary' => 'Bermuda Positive com mensagens positivas.', 'description' => 'Bermuda Positive em sarja com bordado de mensagens positivas. Cintura ajustável, bolsos e modelagem reta.', 'stock' => 0, 'image_url' => 'bermuda-positive', 'categories' => [$catBermudas->id, $catMeninos->id]],
            ['title' => 'Bermuda Tropical', 'price' => 132.90, 'summary' => 'Bermuda Tropical com estampa de folhagens.', 'description' => 'Bermuda Tropical em algodão com estampa de folhagens tropicais. Cintura elástica, fresca e cheia de estilo.', 'stock' => 9, 'image_url' => 'bermuda-tropical', 'categories' => [$catBermudas->id, $catMeninos->id]],
            ['title' => 'Bermuda Andes', 'price' => 102.90, 'summary' => 'Bermuda Andes em tons terrosos.', 'description' => 'Bermuda Andes em sarja couro. Cintura com elástico, modelagem confortável e estilo aventureiro.', 'stock' => 11, 'image_url' => 'bermuda-andes', 'categories' => [$catBermudas->id, $catMeninos->id]],
            ['title' => 'Bermuda Posi', 'price' => 134.90, 'summary' => 'Bermuda Posi com estampa geométrica.', 'description' => 'Bermuda Posi em sarja com estampa geométrica moderna. Cintura ajustável, bolsos funcionais e modelagem reta.', 'stock' => 8, 'image_url' => 'bermuda-posi', 'categories' => [$catBermudas->id, $catMeninos->id]],
            ['title' => 'Bermuda Expedit', 'price' => 137.90, 'summary' => 'Bermuda Expedit estilosa e resistente.', 'description' => 'Bermuda Expedit em sarja resistente com estampa exclusiva. Cintura com elástico e cordão, ideal para aventuras.', 'stock' => 0, 'image_url' => 'bermuda-expedit', 'categories' => [$catBermudas->id, $catMeninos->id]],
            ['title' => 'Bermuda Cena', 'price' => 112.90, 'summary' => 'Bermuda Cena com estampa de paisagem.', 'description' => 'Bermuda Cena em algodão com estampa de paisagem noturna. Cintura elástica, fresca e estilosa.', 'stock' => 10, 'image_url' => 'bermuda-cena', 'categories' => [$catBermudas->id, $catMeninos->id]],
            ['title' => 'Bermuda Spray', 'price' => 74.90, 'summary' => 'Bermuda Spray com efeito grafite.', 'description' => 'Bermuda Spray em algodão com estampa de grafite. Cintura elástica, modelagem despojada e cheia de atitude.', 'stock' => 0, 'image_url' => 'bermuda-spray', 'categories' => [$catBermudas->id, $catMeninos->id]],

            // Blusas
            ['title' => 'Blusa Friends Trip', 'price' => 47.90, 'summary' => 'Blusa Friends Trip com estampa de viagem.', 'description' => 'Blusa em algodão com estampa Friends Trip. Mangas curtas, gola redonda e modelagem confortável. Perfeita para o dia a dia.', 'stock' => 30, 'image_url' => 'blusa-friends-trip', 'categories' => [$catBlusas->id, $catMeninos->id]],
            ['title' => 'Blusa Princesa Vet', 'price' => 36.90, 'summary' => 'Blusa Princesa Vet com brilho e encanto.', 'description' => 'Blusa Princesa Vet em algodão com estampa de princesa e detalhes em glitter. Mangas curtas, gola redonda.', 'stock' => 25, 'image_url' => 'blusa-princesa-vet', 'categories' => [$catBlusas->id, $catMeninas->id]],
            ['title' => 'Blusa Boggie', 'price' => 57.90, 'summary' => 'Blusa Boggie retrô e divertida.', 'description' => 'Blusa Boggie em algodão com estampa retrô. Mangas curtas, modelagem box e gola redonda. Estilo único.', 'stock' => 0, 'image_url' => 'blusa-boggie', 'categories' => [$catBlusas->id]],
            ['title' => 'Blusa Senso', 'price' => 36.90, 'summary' => 'Blusa Senso básica e confortável.', 'description' => 'Blusa Senso em algodão premium liso. Básica e versátil, combina com tudo. Mangas curtas e gola redonda.', 'stock' => 35, 'image_url' => 'blusa-senso', 'categories' => [$catBlusas->id, $catMeninos->id, $catMeninas->id]],
            ['title' => 'Blusa Underwater', 'price' => 42.90, 'summary' => 'Blusa Underwater com tema subaquático.', 'description' => 'Blusa Underwater em algodão com estampa de mundo subaquático. Mangas curtas, gola redonda e cores vibrantes.', 'stock' => 20, 'image_url' => 'blusa-underwater', 'categories' => [$catBlusas->id]],
            ['title' => 'Blusa Stingray', 'price' => 39.90, 'summary' => 'Blusa Stingray com estampa de arraia.', 'description' => 'Blusa Stingray em algodão com estampa de arraia. Mangas curtas, modelagem confortável e design exclusivo.', 'stock' => 22, 'image_url' => 'blusa-stingray', 'categories' => [$catBlusas->id, $catMeninos->id]],
            ['title' => 'Blusa Clean', 'price' => 49.90, 'summary' => 'Blusa Clean com design minimalista.', 'description' => 'Blusa Clean em algodão orgânico com design minimalista. Mangas curtas, gola redonda e caimento perfeito.', 'stock' => 0, 'image_url' => 'blusa-clean', 'categories' => [$catBlusas->id]],
            ['title' => 'Blusa Street', 'price' => 52.90, 'summary' => 'Blusa Street com estilo urbano.', 'description' => 'Blusa Street em algodão com estampa urbana. Mangas curtas, gola redonda e modelagem despojada.', 'stock' => 0, 'image_url' => 'blusa-street', 'categories' => [$catBlusas->id, $catMeninos->id]],
            ['title' => 'Blusa Seahorse', 'price' => 44.90, 'summary' => 'Blusa Seahorse com estampa de cavalo-marinho.', 'description' => 'Blusa Seahorse em algodão com estampa de cavalo-marinho. Mangas curtas, tecido macio e fresco.', 'stock' => 18, 'image_url' => 'blusa-seahorse', 'categories' => [$catBlusas->id]],
            ['title' => 'Blusa Mar', 'price' => 57.90, 'summary' => 'Blusa Mar com estampa oceânica.', 'description' => 'Blusa Mar em algodão com estampa de ondas do mar. Mangas curtas, gola redonda e modelagem confortável.', 'stock' => 0, 'image_url' => 'blusa-mar', 'categories' => [$catBlusas->id]],
            ['title' => 'Blusa Pranchas', 'price' => 51.90, 'summary' => 'Blusa Pranchas com tema de surfe.', 'description' => 'Blusa Pranchas em algodão com estampa de pranchas de surfe. Mangas curtas, gola redonda e estilo praia.', 'stock' => 15, 'image_url' => 'blusa-pranchas', 'categories' => [$catBlusas->id, $catMeninos->id]],
            ['title' => 'Blusa Water Melon', 'price' => 46.90, 'summary' => 'Blusa Water Melon com estampa de melancia.', 'description' => 'Blusa Water Melon em algodão com estampa divertida de melancia. Mangas curtas, gola redonda e fresca.', 'stock' => 20, 'image_url' => 'blusa-water-melon', 'categories' => [$catBlusas->id]],
            ['title' => 'Blusa Cão', 'price' => 42.90, 'summary' => 'Blusa Cão com estampa de cachorro.', 'description' => 'Blusa Cão em algodão com estampa de cachorro. Mangas curtas, gola redonda e modelagem confortável.', 'stock' => 16, 'image_url' => 'blusa-cao', 'categories' => [$catBlusas->id, $catMeninos->id]],
            ['title' => 'Blusa Foguete', 'price' => 44.90, 'summary' => 'Blusa Foguete com estampa espacial.', 'description' => 'Blusa Foguete em algodão com estampa de foguete e estrelas. Mangas curtas, perfeita para pequenos astronautas.', 'stock' => 18, 'image_url' => 'blusa-foguete', 'categories' => [$catBlusas->id, $catMeninos->id]],
            ['title' => 'Blusa Concha', 'price' => 52.90, 'summary' => 'Blusa Concha com estampa de conchas.', 'description' => 'Blusa Concha em algodão com estampa de conchas e elementos marinhos. Mangas curtas, gola redonda.', 'stock' => 14, 'image_url' => 'blusa-concha', 'categories' => [$catBlusas->id, $catMeninas->id]],
            ['title' => 'Blusa Maresia', 'price' => 49.90, 'summary' => 'Blusa Maresia com estampa de brisa marinha.', 'description' => 'Blusa Maresia em algodão com estampa que evoca a brisa do mar. Mangas curtas, modelagem fresca e confortável.', 'stock' => 12, 'image_url' => 'blusa-maresia', 'categories' => [$catBlusas->id]],
            ['title' => 'Blusa Canada', 'price' => 39.90, 'summary' => 'Blusa Canada com estampa da bandeira canadense.', 'description' => 'Blusa Canada em algodão com estampa da folha de bordo. Mangas curtas, gola redonda e modelagem clássica.', 'stock' => 28, 'image_url' => 'blusa-canada', 'categories' => [$catBlusas->id, $catMeninos->id, $catMeninas->id]],
            ['title' => 'Blusa Selo', 'price' => 46.90, 'summary' => 'Blusa Selo com estampa de selos.', 'description' => 'Blusa Selo em algodão com estampa de selos colecionáveis. Mangas curtas, gola redonda e design exclusivo.', 'stock' => 0, 'image_url' => 'blusa-selo', 'categories' => [$catBlusas->id]],
            ['title' => 'Blusa Big Wave', 'price' => 52.90, 'summary' => 'Blusa Big Wave com estampa de ondas gigantes.', 'description' => 'Blusa Big Wave em algodão com estampa de ondas gigantes. Mangas curtas, gola redonda e estilo radical.', 'stock' => 0, 'image_url' => 'blusa-big-wave', 'categories' => [$catBlusas->id, $catMeninos->id]],
            ['title' => 'Blusa Flor de Crochê', 'price' => 39.90, 'summary' => 'Blusa Flor de Crochê com aplicação de flores.', 'description' => 'Blusa Flor de Crochê em algodão com aplicação de flores de crochê. Mangas curtas, delicada e artesanal.', 'stock' => 16, 'image_url' => 'blusa-flor-de-croche', 'categories' => [$catBlusas->id, $catMeninas->id]],

            // Biquínis
            ['title' => 'Biquini Liana', 'price' => 104.90, 'summary' => 'Biquini Liana estiloso para meninas.', 'description' => 'Biquini Liana em tecido UV com estampa floral. Conjunto de duas peças com alças ajustáveis. Proteção solar.', 'stock' => 12, 'image_url' => 'biquini-liana', 'categories' => [$catBiquinis->id, $catMeninas->id]],
            ['title' => 'Biquini Arco Iris', 'price' => 99.90, 'summary' => 'Biquini Arco Iris colorido e divertido.', 'description' => 'Biquini Arco Iris com estampa colorida. Tecido UV com proteção solar, alças ajustáveis e conforto.', 'stock' => 15, 'image_url' => 'biquini-arco-iris', 'categories' => [$catBiquinis->id, $catMeninas->id]],
            ['title' => 'Biquini Susy', 'price' => 116.90, 'summary' => 'Biquini Susy com detalhes em babado.', 'description' => 'Biquini Susy em tecido UV com detalhes em babado. Duas peças com alças ajustáveis, conforto e estilo.', 'stock' => 10, 'image_url' => 'biquini-susy', 'categories' => [$catBiquinis->id, $catMeninas->id]],
            ['title' => 'Biquini UV Primavera', 'price' => 96.90, 'summary' => 'Biquini UV Primavera com proteção solar.', 'description' => 'Biquini UV Primavera em tecido com proteção UV. Estampa primaveril, alças ajustáveis e secagem rápida.', 'stock' => 18, 'image_url' => 'biquini-uv-primavera', 'categories' => [$catBiquinis->id, $catMeninas->id]],
            ['title' => 'Biquini UV Borboletas L', 'price' => 189.90, 'summary' => 'Biquini UV Borboletas com proteção solar premium.', 'description' => 'Biquini UV Borboletas em tecido premium com proteção UV. Estampa de borboletas, alças ajustáveis e conforto.', 'stock' => 8, 'image_url' => 'biquini-uv-borboletas', 'categories' => [$catBiquinis->id, $catMeninas->id]],
            ['title' => 'Biquini UV Oriente', 'price' => 129.90, 'summary' => 'Biquini UV Oriente com estampa oriental.', 'description' => 'Biquini UV Oriente em tecido com proteção solar. Estampa inspirada no oriente, alças ajustáveis e conforto.', 'stock' => 10, 'image_url' => 'biquini-uv-oriente', 'categories' => [$catBiquinis->id, $catMeninas->id]],
            ['title' => 'Biquini UV Dina', 'price' => 147.90, 'summary' => 'Biquini UV Dina com estampa de dinossauros.', 'description' => 'Biquini UV Dina em tecido com proteção UV. Estampa divertida de dinossauros, alças ajustáveis.', 'stock' => 7, 'image_url' => 'biquini-uv-dina', 'categories' => [$catBiquinis->id, $catMeninas->id]],
            ['title' => 'Biquini UV Arcos', 'price' => 109.90, 'summary' => 'Biquini UV Arcos com estampa geométrica.', 'description' => 'Biquini UV Arcos em tecido com proteção UV. Estampa de arcos geométricos, alças ajustáveis.', 'stock' => 12, 'image_url' => 'biquini-uv-arcos', 'categories' => [$catBiquinis->id, $catMeninas->id]],
            ['title' => 'Biquini UV Confete', 'price' => 139.90, 'summary' => 'Biquini UV Confete colorido e alegre.', 'description' => 'Biquini UV Confete com estampa de confetes coloridos. Tecido UV com proteção solar, alças ajustáveis.', 'stock' => 14, 'image_url' => 'biquini-uv-confete', 'categories' => [$catBiquinis->id, $catMeninas->id]],
            ['title' => 'Biquini UV Borboletas', 'price' => 109.90, 'summary' => 'Biquini UV Borboletas delicado e charmoso.', 'description' => 'Biquini UV com estampa de borboletas em tecido com proteção solar. Alças ajustáveis, conforto e estilo.', 'stock' => 16, 'image_url' => 'biquini-uv-jardim', 'categories' => [$catBiquinis->id, $catMeninas->id]],

            // Calças
            ['title' => 'Calça Bento', 'price' => 139.90, 'summary' => 'Calça Bento em sarja. Clássica e resistente.', 'description' => 'Calça Bento em sarja azul. Cintura com elástico e cordão, bolsos laterais e traseiros. Reforço nos joelhos.', 'stock' => 14, 'image_url' => 'calca-bento', 'categories' => [$catCalcas->id, $catMeninos->id]],
            ['title' => 'Calça Run', 'price' => 119.90, 'summary' => 'Calça Run em moletom. Esportiva e confortável.', 'description' => 'Calça Run em moletom cinza. Cintura com elástico e cordão, bolsos laterais. Perfeita para corridas e brincadeiras.', 'stock' => 20, 'image_url' => 'calca-run', 'categories' => [$catCalcas->id, $catMeninos->id, $catMeninas->id]],
            ['title' => 'Calça Suez', 'price' => 87.90, 'summary' => 'Calça Suez em algodão. Leve e fresca.', 'description' => 'Calça Suez em algodão leve. Cintura com elástico, modelagem reta e confortável. Ideal para dias quentes.', 'stock' => 18, 'image_url' => 'calca-suez', 'categories' => [$catCalcas->id, $catMeninos->id]],
            ['title' => 'Calça Practice', 'price' => 82.90, 'summary' => 'Calça Practice em moletom. Confortável para o dia a dia.', 'description' => 'Calça Practice em moletom azul marinho. Cintura elástica, bolsos laterais e punhos. Perfeita para treinos.', 'stock' => 22, 'image_url' => 'calca-practice', 'categories' => [$catCalcas->id, $catMeninos->id]],
            ['title' => 'Calça Lion', 'price' => 144.90, 'summary' => 'Calça Lion em sarja premium.', 'description' => 'Calça Lion em sarja premium azul. Cintura com elástico, bolsos funcionais e modelagem reta. Resistente.', 'stock' => 0, 'image_url' => 'calca-lion', 'categories' => [$catCalcas->id, $catMeninos->id]],
            ['title' => 'Calça Pantacour', 'price' => 49.90, 'summary' => 'Calça Pantacour em tactel. Super leve.', 'description' => 'Calça Pantacour em tactel leve. Cintura elástica, ideal para dias quentes. Prática e confortável.', 'stock' => 30, 'image_url' => 'calca-pantacour', 'categories' => [$catCalcas->id, $catMeninos->id, $catMeninas->id]],
            ['title' => 'Calça Nono', 'price' => 39.90, 'summary' => 'Calça Nono em malha. Conforto e economia.', 'description' => 'Calça Nono em malha básica. Cintura elástica, modelagem reta e confortável. Ótima relação custo-benefício.', 'stock' => 35, 'image_url' => 'calca-nono', 'categories' => [$catCalcas->id, $catMeninos->id]],
            ['title' => 'Calça Juno', 'price' => 52.90, 'summary' => 'Calça Juno estampada. Colorida e alegre.', 'description' => 'Calça Juno em algodão com estampa divertida. Cintura elástica, modelagem reta e fresca.', 'stock' => 20, 'image_url' => 'calca-juno', 'categories' => [$catCalcas->id, $catMeninos->id, $catMeninas->id]],
        ];

        foreach ($products as $data) {
            $categories = $data['categories'];
            unset($data['categories']);

            $slug = $data['image_url'];
            unset($data['image_url']);

            $data['slug'] = $slug;
            $data['status'] = 'active';
            $data['stock'] = $data['stock'] ?? 10;
            $data['brand_id'] = $brand->id;
            $data['type'] = 'simple';

            $product = Product::create($data);

            if (!empty($categories)) {
                $product->categories()->attach($categories);
            }
        }
    }
}
